refactor: remove duplicate template code
siemens/ngx-datatable pull request #117
Opened 2024-11-08 06:12 UTC by chintankavathia

**What kind of change does this PR introduce?** (check one with "x")

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2025-02-26 13:23 UTC, spike-rabbit approved these changes
LGTM, please rebase

2025-02-28 09:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/siemens/ngx-datatable?pullRequest=117) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/siemens/ngx-datatable?pullRequest=117) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/siemens/ngx-datatable?pullRequest=117) it.</sub>

2025-03-10 13:08 UTC, spike-rabbit requested changes
two more things I missed in the last review

2025-03-10 13:08 UTC, spike-rabbit commented on projects/ngx-datatable/src/lib/components/body/body-row-def.component.ts
> +  group: RowOrGroup<unknown>;
this is affecting public API. At least `DataTableRowWrapperComponent` should no be exposed.

I think creating a new interface here would be better

2025-03-11 06:50 UTC, chintankavathia commented on projects/ngx-datatable/src/lib/components/body/body-row-def.component.ts
> +  group: RowOrGroup<unknown>;
removed `rowWrapper` but I am keeping `group` as it make sense to have it here.

2025-03-27 08:24 UTC, spike-rabbit requested changes
Sorry, I missed more stuff the last time:

I would be really awsome, if you just could use the proper names in the template.
So just provide `row` and `group` and make sure that they always end up being set as this in the context of the template

2025-03-27 08:24 UTC, spike-rabbit commented on projects/ngx-datatable/src/lib/components/body/body.component.ts
> +                  @let disabled = isRow(group) && disableRowCheck && disableRowCheck(group);
```suggestion
                  @let disabled = disableRowCheck && disableRowCheck(row);
```

2025-03-27 08:24 UTC, spike-rabbit commented on projects/ngx-datatable/src/lib/components/body/body.component.ts
> +                      group,
```suggestion
                      row: group,
```

2025-03-27 08:24 UTC, spike-rabbit commented on projects/ngx-datatable/src/lib/components/body/body.component.ts
> +            let-group="group"
```suggestion
            let-row="row"
            let-rowIndex="index"
            let-groupValue="groupValue"
            let-disabled="disabled"
```

group seems to be unused, just calling row `row` is more intuitive

2025-03-27 08:24 UTC, spike-rabbit commented on projects/ngx-datatable/src/lib/components/body/body.component.ts
> +              [treeStatus]="!groupRow ? $any(group)?.treeStatus : null"
```suggestion
              [treeStatus]="!groupRow ? $group?.treeStatus : null"
```

Any is no longer needed as treeStatus is included in the row type

2025-03-27 11:11 UTC, spike-rabbit requested changes
Almost good ...

2025-03-27 11:11 UTC, spike-rabbit commented on projects/ngx-datatable/src/lib/components/body/body.component.ts
> +              [treeStatus]="isRow(row) ? row?.treeStatus : null"
```suggestion
              [displayCheck]="displayCheck"
              [treeStatus]="row?.treeStatus"
```

2025-03-27 11:11 UTC, spike-rabbit commented on projects/ngx-datatable/src/lib/components/body/body-row.directive.ts
> +    row: RowOrGroup<TRow>;
```suggestion
    row: TRow;
```

2025-03-27 11:11 UTC, spike-rabbit commented on projects/ngx-datatable/src/lib/components/body/body-row.directive.ts
> +  static ngTemplateContextGuard<TRow extends { treeStatus?: TreeStatus } = any>(
```suggestion
  static ngTemplateContextGuard<TRow extends Row = any>(
```

2025-03-27 11:11 UTC, spike-rabbit commented on projects/ngx-datatable/src/lib/components/body/body-row.directive.ts
> +    groupValue: TRow[];
Seems like this is not needed

2025-03-27 11:11 UTC, spike-rabbit commented on projects/ngx-datatable/src/lib/components/body/body.component.ts
> +              (treeAction)="isRow(row) ? onTreeAction(row) : false"
```suggestion
              (treeAction)="onTreeAction(row)"
```

2025-03-27 12:24 UTC, chintankavathia commented on projects/ngx-datatable/src/lib/components/body/body-row.directive.ts
> +    groupValue: TRow[];
It is needed. its array of grouped rows which is required by body-cell component

2025-03-27 14:04 UTC, spike-rabbit approved these changes
:+1: thx a lot. This is a huge improvement.

2025-03-27 14:05 UTC, merged