ci: setup playwright
siemens/ngx-datatable pull request #124
Opened 2024-11-14 08:41 UTC by chintankavathia

**What kind of change does this PR introduce?** (check one with "x")

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2024-11-18 10:03 UTC, chintankavathia commented on src/app/app-routing.module.ts
> +      useHash: true
Yes. otherwise routing doesn't work with playwright as it reloads the browser page on navigations

2024-11-20 13:19 UTC, spike-rabbit commented
Just two things:
- please avoid at least API changes in this MR. Disabling checks should be fine
- use git lfs to store screenshots

2024-12-10 09:12 UTC, spike-rabbit requested changes
Seems like we have some a11y issues which we should address in another MR soon.

2024-12-10 09:12 UTC, spike-rabbit commented on .github/workflows/test_and_deploy.yml
> +        run: git config remote.origin.lfsurl https://github.com/siemens/ngx-datatable-snapshots.git/info/lfs
I think you can remove this, as we now have `.lfsconfig`

2024-12-10 09:12 UTC, spike-rabbit commented on package.json
> +    "lfs:prepare": "git config remote.origin.lfspushurl https://github.com/siemens/ngx-datatable-snapshots.git/info/lfs && git config remote.origin.lfsurl https://github.com/siemens/ngx-datatable-sna
can be removed

2024-12-10 09:12 UTC, spike-rabbit commented on package.json
> +    "vrt:update": "yarn vrt --update-snapshots",
```suggestion
    "e2e": "playwright test",
    "e2e:update": "yarn e2e --update-snapshots",
```

2024-12-10 09:12 UTC, spike-rabbit commented on package.json
> +    "dotenv-cli": "^7.4.4",
this is not used, right?

2024-12-10 09:12 UTC, spike-rabbit commented on playwright.config.ts
> +// dotenv.config({ path: path.resolve(__dirname, '.env') });
please remove unused code

2024-12-10 09:12 UTC, spike-rabbit commented on playwright.config.ts
> +    // },
please remove them as well

2024-12-10 12:07 UTC, spike-rabbit approved these changes
thx a ton for the this. Should help us a lot to move on without breaking things.

2024-12-10 12:19 UTC, merged