test: add e2e for paging, sorting, selection and others
siemens/ngx-datatable pull request #134
Opened 2024-12-24 10:57 UTC by mistrykaran91

**What kind of change does this PR introduce?** (check one with "x")

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other. (e2e test )

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [x] No

**Other information**:

e2e test for paging, sorting, selection, custom template. Closes #2241

2025-01-07 05:13 UTC, chintankavathia requested changes
@mistrykaran91 Thanks for the PR. I left some comments.

2025-01-07 05:13 UTC, chintankavathia commented on playwright/e2e/selection.spec.ts
> +      await si.runVisualAndA11yTests('name-cell-selection');
cell selection seems to capture a very large height image due to large number of data. can you ensure to only capture snapshot with predefined height width.

2025-01-07 05:13 UTC, chintankavathia commented on playwright/e2e/resize.spec.ts
> +  test(example + ' pinning column', async ({ si, page }) => {
This test is capturing multiple cell text in browser selection mode.

<img width="578" alt="image" src="https://github.com/user-attachments/assets/f188a0d4-b89f-47ba-af4e-5f73c3dc06b1" />

2025-01-07 05:13 UTC, chintankavathia commented on playwright/e2e/sorting.spec.ts
> +  test.describe('server side sorting', () => {
same here. snapshot is having to much content due to large number of rows

2025-01-07 12:52 UTC, mistrykaran91 commented on playwright/e2e/paging.spec.ts
> +      await lastButton.click();
Added extra parameter for ghost-loader

2025-01-08 06:23 UTC, chintankavathia requested changes

2025-01-08 06:23 UTC, chintankavathia commented on playwright/e2e/selection.spec.ts
> +      let rowsWithCheckbox = await page.locator('datatable-body-row input[type=checkbox]').all();
```suggestion
      const rowsWithCheckbox = await page.locator('datatable-body-row input[type=checkbox]').all();
```

2025-01-08 06:23 UTC, chintankavathia commented on playwright/e2e/sorting.spec.ts
> +      await expect(firstRow.getByRole('cell', { name: 'Zolar' })).toBeTruthy();
I think you can remove `await` from all these and just add `await` at their respective locator query.

2025-01-08 06:23 UTC, chintankavathia commented on src/app/paging/paging-virtual.component.scss
> +::ng-deep .datatable-footer .datatable-pager a {
Don't use `ng-deep`. you can simply override the css variable instead of overriding specific style

2025-01-08 06:23 UTC, chintankavathia commented on src/app/paging/paging-client.component.ts
> +      ::ng-deep .datatable-footer .datatable-pager a {
not needed just override the css variable

2025-01-08 07:19 UTC, mistrykaran91 commented on playwright/e2e/sorting.spec.ts
> +      await expect(firstRow.getByRole('cell', { name: 'Zolar' })).toBeTruthy();
Removed `await` from `toBeTruthy`

2025-01-08 07:39 UTC, chintankavathia approved these changes
LGTM.
@spike-rabbit feel free to review or merge

2025-01-21 09:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/siemens/ngx-datatable?pullRequest=134) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/siemens/ngx-datatable?pullRequest=134) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/siemens/ngx-datatable?pullRequest=134) it.</sub>

2025-01-21 13:36 UTC, spike-rabbit commented
@mistrykaran91 / @chintankavathia  it seems like the screenshots are missing on the git-lfs repo. Can you check where they are?

2025-01-22 11:09 UTC, chintankavathia commented on package.json
> +    "e2e:prepare": "playwright install --with-deps chromium",
```suggestion
    "e2e:prepare": "playwright install",
```

2025-01-31 14:58 UTC, spike-rabbit commented on playwright/e2e/paging.spec.ts
> +      await si.visitExample(example, false);
```suggestion
      await si.visitExample(example);
```

the autoscaling was removed, so please adjust every call that was setting this to false.

2025-02-03 13:14 UTC, spike-rabbit commented
thx a lot :rocket: 

This should help us to move on without creating to many unintended changes.

2025-02-03 13:14 UTC, merged