Angular 15 compatibility
siemens/ngx-datatable pull request #39
Opened 2023-07-07 19:59 UTC by fanil-kashapov

**What kind of change does this PR introduce?** (check one with "x")

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the new behavior?**
Update to angular 15

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [x ] No

2023-07-08 14:02 UTC, fh1ch requested changes
@fanil-kashapov thanks a ton for this great MR, we appreciate this a lot 🙇 

A few general input/questions from my end, otherwise this one is good to go. Let me know what you think, back to you 🏓

2023-07-10 20:51 UTC, fanil-kashapov commented on angular.json
> +    "analytics": "bb52b033-97ca-4c6f-bbce-8db89400f162"
will disable,  it was automatically added by  'ng update' command

2023-07-10 21:43 UTC, fanil-kashapov commented on tsconfig.json
>      "module": "es2020",
all updates to ES were provided by 'ng update' command, should I move it back to es2018?

2023-07-11 08:33 UTC, fanil-kashapov commented on package.json
> +    "@angular/router": "^15.2.9",
Done

2023-07-14 06:36 UTC, fanil-kashapov reviewed
Thx for review, done

2023-10-02 22:22 UTC, rampency commented
can we merge this?

2023-11-01 18:29 UTC, supremeqwert commented
Can this pr address the current issue with importing styles into css present in https://github.com/swimlane/ngx-datatable/issues/2162 ? Also what remains for this to be merged @fh1ch

2023-12-01 18:05 UTC, thatcort commented
Hi, can this PR be merged?

2023-12-12 15:29 UTC, fh1ch approved these changes
Huge thanks for the rework and sorry for the delay here 🙇 

All findings addressed and no new questions from my end, so let's get this released.

2023-12-12 15:30 UTC, merged