fix: two way binding for offset
siemens/ngx-datatable pull request #45
Opened 2024-03-13 05:52 UTC by chintankavathia

Allows to keep external pagination components to be in sync with offset value.

**What kind of change does this PR introduce?** (check one with "x")

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here) 
external pagination component will not update the page number when user sort the columns

**What is the new behavior?**
external pagination component's page number stays in sync with the datatable offset value.

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2024-03-13 05:56 UTC, chintankavathia commented
@timowolf Could you please review this one?

2024-03-18 12:00 UTC, timowolf requested changes

2024-03-18 12:00 UTC, timowolf commented on projects/ngx-datatable/src/lib/components/datatable.component.ts
> +    });
I would move it below `this.bodyComponent.updateOffsetY(this.offset);`. So internals are computed first. Also consistent with ` onFooterPage(event: any)`.

2024-03-19 06:46 UTC, timowolf approved these changes
Many thanks. Looks good to me.

2024-03-19 06:47 UTC, merged

2024-04-26 12:09 UTC, Hrudwolf commented
I've noticed an issue following the integration of PR #45, particularly concerning the interaction between server-side paging and sorting. When sorting a column, the application makes two server calls: one for paging and another for sorting. 

With this change, there is no distinction between retrieving page data and applying sorting.
And because the `sort.emit` is triggered after the `page.emit` we cannot apply the sort to getting the page data.

A suggested fix would be to swap the page and sort emits around or not call `page.emit` if `externalPaging` is `true`.

2024-04-29 05:48 UTC, chintankavathia commented
> I've noticed an issue following the integration of PR #45, particularly concerning the interaction between server-side paging and sorting. When sorting a column, the application makes two server calls: one for paging and another for sorting.
> 
> With this change, there is no distinction between retrieving page data and applying sorting. And because the `sort.emit` is triggered after the `page.emit` we cannot apply the sort to getting the page data.
> 
> A suggested fix would be to swap the page and sort emits around or not call `page.emit` if `externalPaging` is `true`.

The order here is correct. sort should trigger only after the page offset is reset to 0. Yes in case of external paging it can lead to multiple server calls but that can easily be avoided using `switchMap`.

2025-02-05 11:48 UTC, amelnikoff commented
So for anyone else finding this PR, safe version is [22.1.0]

2025-02-05 13:16 UTC, amelnikoff commented
Nah, this is suffering from using old open source project. Siemens team has same problem ;) I don't think that their managers supporting development of OSS.

2025-02-05 14:03 UTC, timowolf commented
@talamaska @amelnikoff we hear you, but priorized a general rework of the project structure first.

2025-02-07 10:20 UTC, talamaska commented
We are listening to both events. In what world sorting changes the page? No matter if it is backend or just front end, assuming the user wanted to change the page when sorting is not supported by any real UAT. Again the change was introduced as a minor release, which is unacceptable. There is no way to opt-out this new behaviour. The suggested approach with event source is ok-ish if it will help us prevent complicated rxjs logic to avoid duplicated requests. We are performing backend sorting and pagination, I did't quite understand what are @timowolf saying about this change being made for exactly this. Hopefully this will be resolved soon.

2025-06-27 04:31 UTC, spike-rabbit commented
FYI, in v23 the page event now also contains `sorts` which turns this effectively into the external / server state change event we were planning. 

Since sorting will always reset the page and thus emit a page event, this should allow lazy data loading by only listening to one event. Note that the page event is still emitted on sort, even if the page itself was not actually changed.