fix: improve types for row grouping
siemens/ngx-datatable pull request #81
Opened 2024-09-26 06:53 UTC by spike-rabbit

**What kind of change does this PR introduce?** (check one with "x")

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")

- [x] Yes, but the note is already merged
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2024-09-26 11:05 UTC, timowolf requested changes
Thanks, this makes sense. I added some comments. Maybe we can merge 2 types. Rebase and place to the new types to public or internal and if possible, write some documentation to the event types.

2024-09-26 11:05 UTC, timowolf commented on projects/ngx-datatable/src/lib/types/group.events.ts
> +export interface GroupToggleEvent<TRow> {
Rebase and put in public types.

2024-09-26 11:06 UTC, timowolf commented
@spike-rabbit Back to you :-)

2024-09-26 11:30 UTC, timowolf requested changes
No other review, find my comments. I pressed the re-request review button by accident.

2024-09-27 06:50 UTC, spike-rabbit commented on projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.ts
> +    (this.rowContext ?? this.groupContext).rowIndex = val;
I am against merging. Those types just share two properties. The others are different.
```ts
export interface GroupContext<TRow> {
  group: Group<TRow>;
  expanded: boolean;
  rowIndex: number;
}

export interface RowDetailContext<TRow> {
  row: TRow;
  expanded: boolean;
  rowIndex: number;
  disableRow$?: Observable<boolean>;
}
```

They are emitted by different directives (`DatatableGroupHeaderTemplateDirective` and `DatatableRowDetailTemplateDirective`) so merging them would make them bad as we have properties in there which are never used in certain context. 

Sure, the code looks bad this way, but we need to find a better solution in another MR.  Merging the interface is far more worse in my opinion as this has a negative impact on consumer.

2024-09-27 06:53 UTC, spike-rabbit commented on projects/ngx-datatable/src/lib/types/group.events.ts
> +export interface AllGroupsToggleEvent {
It is part of the `GroupToggleEvents` . The `AllGroupsToggleEvent` type is indirectly used in `DatatableGroupHeaderDirective#expandAllGroups`

2024-09-27 06:54 UTC, spike-rabbit commented on projects/ngx-datatable/src/lib/types/group.events.ts
> +export interface GroupToggleEvent<TRow> {
done

2024-09-27 08:18 UTC, timowolf commented
@spike-rabbit I think the body component should also make use of the new toggle types.

2024-09-30 09:26 UTC, spike-rabbit commented
No longer needed

2024-09-30 09:26 UTC, closed without merging