refactor: use inject api instead of constructor for DI
siemens/ngx-datatable pull request #92
Opened 2024-10-03 09:08 UTC by chintankavathia

**What kind of change does this PR introduce?** (check one with "x")
Switch to `inject` syntax instead of using constructor style DI 

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2024-10-04 07:00 UTC, timowolf requested changes
Looks good. Many thanks, just one question?

2024-10-04 07:00 UTC, timowolf commented on projects/ngx-datatable/src/lib/directives/orderable.directive.spec.ts
This change of the test file seems not related. Is it intended?

2024-10-04 08:55 UTC, chintankavathia commented on projects/ngx-datatable/src/lib/directives/orderable.directive.spec.ts
It is required as it was wrongly creating directive instances using constructor calls before. now with this migration angular will throw error when inject gets called out of injector context.

2024-10-08 07:36 UTC, spike-rabbit requested changes
Looks good, just a few things I noticed that were also wrong before but related

2024-10-08 07:36 UTC, spike-rabbit commented on projects/ngx-datatable/src/lib/components/body/body-row.component.ts
> +  private scrollbarHelper = inject(ScrollbarHelper, { skipSelf: true });
```suggestion
  private scrollbarHelper = inject(ScrollbarHelper);
```

`ScrollbarHelper` is provided in the module. So for me it looks like skipSelf is pointless and we can just remove it

2024-10-08 07:36 UTC, spike-rabbit commented on projects/ngx-datatable/src/lib/components/columns/column-cell.directive.ts
> +  template = inject<TemplateRef<any>>(TemplateRef);
```suggestion
  template = inject<TemplateRef<CellContext>>(TemplateRef);
```

2024-10-08 07:36 UTC, spike-rabbit commented on projects/ngx-datatable/src/lib/components/datatable.component.ts
> +  private dimensionsHelper = inject(DimensionsHelper, { skipSelf: true });
```suggestion
  private scrollbarHelper = inject(ScrollbarHelper);
  private dimensionsHelper = inject(DimensionsHelper);
```

Both are provided in the module. So for me it looks like skipSelf is pointless and we can just remove it

2024-10-08 07:36 UTC, spike-rabbit commented on projects/ngx-datatable/src/lib/components/header/header.component.ts
> +  private scrollbarHelper = inject(ScrollbarHelper, { skipSelf: true });
```suggestion
  private scrollbarHelper = inject(ScrollbarHelper);
```

2024-10-09 06:41 UTC, timowolf approved these changes
LGTM

2024-10-09 06:42 UTC, merged